ALTER TABLE PERFIL 
DROP CONSTRAINT PERFIL_USUARIOP_FK;

ALTER TABLE PERFIL RENAME COLUMN USUARIOP_ID TO ID_AUTH_USER;

ALTER TABLE PERFIL
ADD CONSTRAINT PERFIL_AUTH_USER_FK FOREIGN KEY
(
  ID_AUTH_USER 
)
REFERENCES AUTH_USER
(
  ID 
)
ENABLE;

drop table usuariop;