# Generated by Django 3.2.8 on 2021-10-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('tipo_actividad', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fec_aviso', models.DateField()),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id_asesoria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cant_asistentes', models.CharField(max_length=2)),
                ('materiales', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.BigIntegerField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteContrato',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cliente_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fec_inicio', models.DateField()),
                ('fec_termino', models.DateField()),
                ('fec_corte', models.DateField()),
                ('fec_pago', models.DateField()),
                ('pago_mensual', models.BigIntegerField()),
                ('pago_extra', models.BigIntegerField()),
                ('total_pago', models.BigIntegerField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id_lista', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=250)),
                ('is_valid', models.FloatField()),
                ('recomendacion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mejoras',
            fields=[
                ('id_mejora', models.BigIntegerField(primary_key=True, serialize=False)),
                ('propuesta', models.CharField(max_length=250)),
                ('aceptacion', models.FloatField()),
            ],
            options={
                'db_table': 'mejoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fec_estimada', models.DateField()),
                ('fec_ida', models.DateField()),
            ],
            options={
                'db_table': 'pac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_perf', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('costo', models.BigIntegerField()),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_prof', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cant_asesoria', models.BigIntegerField()),
                ('cant_llamadas', models.BigIntegerField()),
                ('cant_visitas', models.BigIntegerField()),
                ('cant_accidentes', models.BigIntegerField()),
                ('cant_multas', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAsesoria',
            fields=[
                ('id_tipo_ase', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id_tipo_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_extra', models.FloatField()),
            ],
            options={
                'db_table': 'visita',
                'managed': False,
            },
        ),
    ]
