# Generated by Django 3.2.8 on 2021-11-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuariop',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuariop',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pac',
        ),
    ]
