# Generated by Django 3.2.8 on 2021-10-26 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('tipo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fec_aviso', models.DateField()),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fec_inicio', models.DateField()),
                ('fec_termino', models.DateField()),
                ('fec_vencimiento', models.DateField()),
                ('fec_pago', models.DateField()),
                ('pago_mensual', models.BigIntegerField()),
                ('pago_extra', models.BigIntegerField()),
                ('total_pago', models.BigIntegerField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mejoras',
            fields=[
                ('id_mejora', models.BigIntegerField(primary_key=True, serialize=False)),
                ('propuesta', models.CharField(max_length=250)),
                ('aceptacion', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'mejoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('fec_registro', models.DateField()),
                ('vigente', models.CharField(max_length=1)),
                ('tipo_perf', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cant_visita', models.BigIntegerField()),
                ('cant_asesoria', models.BigIntegerField()),
                ('cant_llamadas', models.BigIntegerField()),
                ('cant_visitas', models.BigIntegerField()),
                ('cant_accidentes', models.BigIntegerField()),
                ('cant_multas', models.BigIntegerField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAsesoria',
            fields=[
                ('id_tipo_ase', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id_tipo_reporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_perfil', models.OneToOneField(db_column='id_perfil', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.perfil')),
                ('id_admin', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_pat', models.CharField(max_length=40)),
                ('apellido_mat', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.actividad')),
                ('id_asesoria', models.BigIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.actividad')),
                ('id_capacitacion', models.BigIntegerField(unique=True)),
                ('cant_asistentes', models.CharField(max_length=2)),
                ('materiales', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_perfil', models.OneToOneField(db_column='id_perfil', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.perfil')),
                ('id_cli', models.BigIntegerField(unique=True)),
                ('cli_razon_social', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_perfil', models.OneToOneField(db_column='id_perfil', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.perfil')),
                ('id_prof', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_pat', models.CharField(max_length=40)),
                ('apellido_mat', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_actividad', models.OneToOneField(db_column='id_actividad', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.actividad')),
                ('id_visita', models.BigIntegerField(unique=True)),
                ('is_extra', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'visita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteContrato',
            fields=[
                ('id_cli', models.OneToOneField(db_column='id_cli', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.cliente')),
            ],
            options={
                'db_table': 'cliente_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('descripcion', models.CharField(max_length=250)),
                ('is_valid', models.CharField(max_length=1)),
                ('recomendacion', models.CharField(max_length=250)),
                ('id_prof', models.OneToOneField(db_column='id_prof', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.profesional')),
            ],
            options={
                'db_table': 'lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pac',
            fields=[
                ('fec_estimada', models.DateField()),
                ('fec_ida', models.DateField()),
                ('id_cli', models.OneToOneField(db_column='id_cli', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.cliente')),
            ],
            options={
                'db_table': 'pac',
                'managed': False,
            },
        ),
    ]
