# Generated by Django 3.2.8 on 2021-11-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('tipo_act', models.CharField(choices=[('1', 'Capacitación'), ('2', 'Asesoría'), ('3', 'Visita'), ('4', 'Asignar')], max_length=1, verbose_name='Tipo de actividad')),
                ('act_extra', models.BooleanField()),
                ('fec_creacion', models.DateField(auto_now_add=True)),
                ('fec_estimada', models.DateField(verbose_name='Fecha estimada')),
                ('fec_ida', models.DateField(blank=True, null=True, verbose_name='Fecha ida')),
                ('estado', models.CharField(choices=[('1', 'Solicitado'), ('2', 'Pendiente'), ('3', 'Realizado'), ('4', 'Cancelado')], max_length=1)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('fec_aviso', models.DateField()),
                ('descripcion', models.CharField(max_length=300)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'alerta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id_asesoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('fec_emision_bol', models.DateField()),
                ('fec_pago', models.DateField()),
                ('fec_corte', models.DateField()),
                ('pago_mensual', models.BigIntegerField()),
                ('pagado', models.BooleanField()),
                ('pago_extra', models.BigIntegerField()),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id_capacitacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cant_asistentes', models.CharField(max_length=2)),
                ('materiales', models.CharField(max_length=250)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'capacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=500)),
                ('fec_mensaje', models.DateTimeField()),
                ('enviado_por', models.CharField(max_length=30)),
                ('cabecera', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('fec_inicio', models.DateField()),
                ('fec_termino', models.DateField()),
                ('total_pago', models.BigIntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id_lista', models.BigIntegerField(primary_key=True, serialize=False)),
                ('lista', models.CharField(max_length=1000)),
                ('verificacion', models.CharField(max_length=500)),
                ('recomendacion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'lista',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mejora',
            fields=[
                ('id_mejora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('propuesta', models.CharField(max_length=250)),
                ('aceptacion', models.BooleanField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'mejora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.BigIntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('tipo_perf', models.CharField(choices=[('1', 'Administrador'), ('2', 'Profesional'), ('3', 'Cliente')], max_length=1)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
                'default_related_name': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('costo', models.BigIntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_prof', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('cant_asesoria', models.BigIntegerField()),
                ('cant_llamadas', models.BigIntegerField()),
                ('cant_visitas', models.BigIntegerField()),
                ('cant_accidentes', models.BigIntegerField()),
                ('cant_multas', models.BigIntegerField()),
                ('fec_emision', models.DateField()),
            ],
            options={
                'db_table': 'reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAsesoria',
            fields=[
                ('id_tipo_ase', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_asesoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id_tipo_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_reporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id_visita', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'visita',
                'managed': False,
            },
        ),
    ]
