# Generated by Django 3.2.8 on 2021-10-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=500)),
                ('fec_mensaje', models.DateTimeField()),
                ('enviado_por', models.CharField(max_length=30)),
                ('cabecera', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
    ]
