# Generated by Django 3.2.8 on 2021-11-05 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211105_0026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuariop',
        ),
    ]
