# Generated by Django 3.2.8 on 2021-11-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_usuariop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'managed': True},
        ),
    ]
