# Generated by Django 3.2.8 on 2021-11-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_lista_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lista',
            options={'managed': False},
        ),
    ]
