# Generated by Django 3.2.8 on 2021-11-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_lista_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mejora',
            fields=[
                ('id_mejora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('propuesta', models.CharField(max_length=250)),
                ('aceptacion', models.BooleanField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'mejoras',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Mejoras',
        ),
    ]
