# Generated by Django 3.2.8 on 2021-11-16 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211108_2056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mejora',
            table='mejora',
        ),
    ]
