# Generated by Django 3.2.8 on 2021-11-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mejora_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fec_emision_bol', models.DateField()),
                ('fec_pago', models.DateField()),
                ('fec_corte', models.DateField()),
                ('pago_mensual', models.BigIntegerField()),
                ('pagado', models.FloatField()),
                ('pago_extra', models.BigIntegerField()),
            ],
            options={
                'db_table': 'boleta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ClienteContrato',
        ),
    ]
