# Generated by Django 3.2.8 on 2021-11-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211117_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
